version: '2.1'

orbs:
  aws-ecr: circleci/aws-ecr@9.0
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecs: circleci/aws-ecs@4.0

executors:
  node:
    docker:
      - image: cimg/aws:2024.03.1

jobs:
  test: 
    docker:
      - image: cimg/node:22.7.0
    steps:
      - checkout
      - run:
          name: "Install package"
          command: npm install
      - run:
          name: "Test" 
          command: npm test
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: npm ci --omit=dev
      - setup_remote_docker:
          version: docker24
      - aws-ecr/build_and_push_image:
          account_id: $AWS_ACCOUNT_ID
          auth:
            - aws-cli/setup:
                region: $AWS_REGION
          push_image: true
          repo: $AWS_RESOURCE_NAME_PREFIX
          tag: $CIRCLE_SHA1
          region: $AWS_REGION

workflows:
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - staging
                - master
                - feature/test_deploy
      - aws-ecs/deploy_service_update:
          name: deploy
          auth:
            - aws-cli/setup:
                region: $AWS_REGION
          cluster: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container_image_name_updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          filters:
            branches:
              only:
                - develop
                - staging
                - master
                - feature/test_deploy
          requires:
            - build
