version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.1
  aws-ecs: circleci/aws-ecs@5.0.0

workflows:
  setup-and-test:
    jobs:
      - test
  docker-build-and-deploy:
    jobs:
      - build-and-deploy

jobs:
  test:
    docker:
      - image: cimg/node:22.7.0
    steps:
      - checkout
      - run:
          name: "Install package"
          command: npm install
      - run:
          name: "Test" 
          command: npm test
      # - run: 
      #     name: "Test e2e"
      #     command: npm test:e2e
  build-and-deploy:
    - aws-ecr/build-and-push-image:
        dockerfile: Dockerfile
        path: .
        repo: ${PROJECT_PREFIX}
        tag: '${CIRCLE_SHA1}'
    # - aws-ecs/deploy-service-update:
    #     requires:
    #       - aws-ecr/build-and-push-image # only run the deployment job once the build and push image job has completed
    #     family: '${PROJECT_PREFIX}-service'
    #     cluster: '${PROJECT_PREFIX}-cluster'
    #     container-image-name-updates: 'container=${PROJECT_PREFIX}-service,tag=${CIRCLE_SHA1}'